language: erlang
sudo: false
otp_release:
# Test on all supported releases & some more
   - 23.1.2
   - 22.3
   - 21.3
   - 20.3
   - 19.3
   - 18.3
   - 17.5

script:
  - make
  - make dialyze

notifications:
  email: false
